### ISSUE TITLE
Highlight that .gitlab-ci.yml can be put in another repository (permissions to edit)

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#101]
https://docs.gitlab.com/ee/user/project/pipelines/settings.html#custom-ci-configuration-path

- Developers cannot edit the YAML no more, since the location is specified in the project settings.

**Comment by htriem** [comment]
We think this is a bit too advanced for GitLab Basic and we will consider this for GitLab Advanced.
