### ISSUE TITLE
Add screenshots of goto for online trainings

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#111]
this will help find the "raise hand feature" faster

we should do that together, and include different views from browser / native apps from different OS

**Comment by htriem** [comment]
Since there is another training happening right now, I'd need to create those screenshots on a monday, especially with how different goToTraining tends to look on different operating systems.

**Comment by theFeu** [comment]
Absoutely :)
Thanks for remembering. :)

**Comment by htriem** [comment]
I've taken the relevant screenshots a while ago - how useful are they now considering we're planning on using a different training tool?

**Comment by theFeu** [comment]
Not very, I am afraid...
Will close this and open a new issue to change to BBB instructions
