### ISSUE TITLE
Make an introduction slide

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#117]
Add a slide to the beginning with some key words like:
* name
* company
* role in company / daily business
* experiences with git
* expectations for this training

**Comment by martialblog** [comment]
Where should we place this? First slide? After Netways intro?

**Comment by theFeu** [comment]
I think I would prefer after the Netways intro á la "This is who we are, who are you?"

Not sure where the trainer slide that is described in the README pops up - we should try not to duplicate the intro of the trainer.

Personally I think this slide could replace the trainer introduction slide, because they can just tell you about them with the slide.

What do you think?

**Comment by martialblog** [comment]
After the Netways Intro sounds good. 

If possible this slide could then be omitted in the printout

**Comment by theFeu** [comment]
We have the `!SLIDE smbullets noprint` notation to do that :)

**Comment by theFeu** [comment]
I'll reopen this really quick, because in the README we still have the section that asks to add a trainer slide.
