### ISSUE TITLE
Create a Linux console cheatsheet to be handed out

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#119]
That cheatsheet should include:

unix: ls, cd, mkdir and vi
vi: insert mode, exit with and without saving, delete line, yank line, paste line
markdown: headers, lists, bold, code

**Comment by theFeu** [comment]
I think this should be very helpful for upcoming in-person trainings.

We need to coordinate this with the events team, so we get the handout printed out for each trainee.

**Comment by htriem** [comment]
Can we discuss in what format this should be drafted - especially in coordination with training? I have a draft, but no idea where it is supposed to go.

**Comment by theFeu** [comment]
I would say we make a printable PDF and add it to the release.
This way the events team can print it and send it out via mail with the rest of the handouts.

**Comment by martialblog** [comment]
We will try to create a central place for a Linux Cheatsheet for all trainings

**Comment by theFeu** [comment]
Update on this: colleague started working on creating a cheat sheet that can be made available for more trainings than this one - @MisterMountain if I recall correctly :)

**Comment by martialblog** [comment]
See https://github.com/NETWAYS/training-global/pull/15

**Comment by martialblog** [comment]
We now have some Linux cheatsheets in training-global. Can be downloaded or viewed in the browser
