### ISSUE TITLE
Do not ignore the gitignore but use git/info/exclude instead

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#130]
Do a research and maybe adapt

**Comment by martialblog** [comment]
As discussed, I'd rather add a hint about the global excludesfile

```
[core]
    excludesfile = ~/.gitignore
```

**Comment by theFeu** [comment]
I think I would prefer a hint about this section from the [Atlassian docs](https://www.atlassian.com/git/tutorials/saving-changes/gitignore#:~:text=If%20you%20want%20to%20ignore,directory%20as%20an%20ignored%20file.)

> *Personal Git ignore rules*
> You can also define personal ignore patterns for a particular repository in a special file at .git/info/exclude. These are not versioned, and not distributed with your repository, so it's an appropriate place to include patterns that will likely only benefit you. For example if you have a custom logging setup, or special development tools that produce files in your repository's working directory, you could consider adding them to .git/info/exclude to prevent them from being accidentally committed to your repository.
