### ISSUE TITLE
Find a different way of making a docker image available for usage in CI/CD

### ISSUE THREAD

**Issue by htriem** [NETWAYS/gitlab-training#136]
https://docs.docker.com/docker-hub/download-rate-limit/
Since Docker Hub has added download limits in November 2020, we noticed in our last training that with a regular amount of trainees doing the CI/CD exercises that those limits are being reached, rendering the last exercises in that chapter impossible to successfully execute.

We need to find a different solution for getting the Docker base image, preferably a solution which is readily available in our exercises, especially if we manage to host the solution ourselves.

**Comment by theFeu** [comment]
Looked around for a bit but decided that I am probably better off asking experts, so I did just that.
https://twitter.com/the_FeuFeu/status/1405781901139496961?s=20

**Comment by martialblog** [comment]
We could either

1. use the GitHub Container Registry and mirror some Images here
2. use the internal GitLab and mirror/provide Images there

**Comment by htriem** [comment]
Shouldn't this be fixed by now since our hosting provider has a mirror?

**Comment by martialblog** [comment]
We assume it's fixed and if not, we reopen and think of something.
