### ISSUE TITLE
Evaluate Pandoc for converting README.md to README.html

### ISSUE THREAD

**Issue by htriem** [NETWAYS/gitlab-training#137]
While the solution using Python and Pygments is working like a charm, new types of exercises/tests/demonstrations for CI/CD would be welcome. It might be a good idea to take a look at Pandoc and it's usefulness for the exercises.

**Comment by dnsmichi** [comment]
IIRC using pandoc would have caused students to type much more, causing more errors than using a Python module. Side benefit of the exercise was that students learn how to install dependencies in a CI/CD job. One possible iteration could be using a requirements.txt in the repo first, and then run `pip install -r requirements.txt` in the before_script section.

Part of the 2019 OSMC workshop and advanced training material was building Go code. In my community workshops at GitLab, I have been expanding on this and we built a Go Tanuki to fix and build, and run. Could be an idea for you as well.

https://about.gitlab.com/handbook/marketing/community-relations/developer-evangelism/projects/#workshops has more insights and links the template repository.
