### ISSUE TITLE
Evaluate whether the new pricing comparison is worth reading

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#140]
https://about.gitlab.com/pricing/self-managed/feature-comparison/

**Comment by htriem** [comment]
My take: We should visualize the pricing model and take all references to a certain model out of the training - this stuff has changed way too often to have anything hard coded into the training. 

At most, there should be a single slide, linking to the current pricing model, so there is little in the way of preperation before the next training. 

Would it make sense to compare offers from managed hosting providers as well?

**Comment by theFeu** [comment]
I do agree, that it makes very little sense to go into detail about the pricing.
For one, because it gets changed a lot, but I also see very little relevance to the people visiting the training since 99% of then are sent by companies that have their own GitLab.

Linking the pricing page on GitLab and quickly showing it would be the best solution imho

**Comment by theFeu** [comment]
@martialblog and I agreed that it really is not.

The three tiers can be summarised with:
- Basic features (Private users and small teams)
- Some administrative features (Teams that need more organisation and authentification)
- Security features (For companies that need it)
