### ISSUE TITLE
Fix GitHub Actions upload artifacts

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/gitlab-training#161]
There's some wicked loop happening in the upload artifacts GitHub Action

```
./global/
./global/global/
./global/global/global/
./global/global/global/global/
./global/global/global/global/global/
```

**Comment by martialblog** [comment]
https://github.com/NETWAYS/training-global/blob/master/global

J'accuse!

**Comment by theFeu** [comment]
Oh!

Turn to `/master/global/.keep` ?

**Comment by martialblog** [comment]
This should fix it https://github.com/NETWAYS/training-global/pull/7 

We needs to update the subtree afterwards.

**Comment by martialblog** [comment]
We will disable the GH Actions, since we upload the PDFs manually

**Comment by martialblog** [comment]
I disabled the Actions since we upload rarely and manually
