### ISSUE TITLE
Extend and or update git hook slides

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/gitlab-training#162]
Maybe we should extend and or update the git hook slide

An example could be this table:

https://gitlab.com/gitlab-org/gitlab/-/issues/196051

**Comment by martialblog** [comment]
Should be maybe differentiate between client side and server side hooks, plus hooks that GitLab offers (system, server, web)?

**Comment by mocdaniel** [comment]
Imho git-hooks - to a wide extent - are outside of the scope of a **fundamentals** training. We can of course update the slide(s), but I wouldn't go into any more details.

**Comment by theFeu** [comment]
We originally included them only as an info that those things are possible, without elaborating too much.

I think we should update the info so it's correct, with two or three expamples with what is possible. But no exercises etc nessessary imho

**Comment by htriem** [comment]
Yes, I'd agree with @theFeu. An example of how it might work would be nice, but for the fundementals training using hooks might be a step too far. 

There are too many certain use cases with other software that we would be able to cover everything anyways.

**Comment by martialblog** [comment]
At the moment we have 4 slides under integrations:

- git hooks
- client hooks
- server hooks
- web hooks

My proposal:

- combine the client and server hooks into one slide (plus fix the note about GitLab support)
- remove the web hook slide

**Comment by theFeu** [comment]
"Hooks are a thing, here are two use cases, if you are interested check the GitLab docs for more" sounds like the way to go!
