### ISSUE TITLE
Repetition slide mentions merge but was not mention in the training yet

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/gitlab-training#175]
Repetition slide mentions merge but was not mention in the training yet

**Comment by theFeu** [comment]
The repitition has been shortened to one slide and is a little clearer to understand now.

I am still not 100% sure if I want to keep it as a slide or maybe go back to having it as a loose file / a snippet to share.

For now I would leave it like this and then change if it still feels out of place after my next training in jan 2023
