### ISSUE TITLE
Double-check if Centos7 is still the base OS for training notebooks/VMs

### ISSUE THREAD

**Issue by mocdaniel** [NETWAYS/gitlab-training#194]
I'm not entirely sure but think the mid-term goal is to have all trainings move from CentOS 7 to CentOS Stream 9. We should double-check and adapt the slides explaining the training environment accordingly.

**Comment by martialblog** [comment]
Good point. I will check our Provisioning Code and update the CentOS Version

**Comment by martialblog** [comment]
We updated it to just say CentOS, should be fine for the future... unless we switch to Rocky or Alma or whatever
