### ISSUE TITLE
Make a lab for building a release

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#200]
Maybe as an addition to the CI / CD chapter to have the html be uploaded into the release

https://docs.gitlab.com/ee/user/project/releases/

**Comment by theFeu** [comment]
I think it would be cool to have a manual job that you can trigger on each commit that builds a release for you.
This way we can explore different triggers in the CI and also have a release process that is readily available for every commit.

**Comment by martialblog** [comment]
@theFeu I like the idea. Gives us a chance to introduce the `when` keyword
