### ISSUE TITLE
Adapt CI to switch to the python container at a later point

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#201]
It cool to show that you can write bash in the container and install and use stuff to alpine, but it would make sense to later switch to a python image

**Comment by martialblog** [comment]
I like the idea.

We could maybe add a "CI tips and tricks" or "best practices" section. We could then:

- Ask the trainees at some point: "what could be improved in our pipeline"
- Either let them do it, or the trainer show it

**Comment by dnsmichi** [comment]
Suggest adding the pipeline efficiency docs, https://docs.gitlab.com/ee/ci/pipelines/pipeline_efficiency.html specifically how to optimize images https://docs.gitlab.com/ee/ci/pipelines/pipeline_efficiency.html#docker-images 

A common mistake is to use large base images, with wasting resources, or creating slow pipelines unintentionally.

**Comment by martialblog** [comment]
@dnsmichi Hey Michi! I absolutely agree. Thanks for the hints.
