### ISSUE TITLE
Show differences in working area between branches in the stash lab

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#203]
When we show git stash we already know about branches and switching.

We should make a lab where we want to fix a typo somwhere else and need to switch braches (and for that stash our current changes).

**Comment by martialblog** [comment]
I though about this and tested some ideas for a Lab. However, depending on what the participants do there might be merge conflics, which we did not cover at that point.

**Comment by martialblog** [comment]
For now I vote that we keep it as is. Since I don't want people running into merge conflicts at this point of the training

**Comment by martialblog** [comment]
Closing this for now. Can be reopened if we still want to change this.
