### ISSUE TITLE
Restructure the Gitflow Workflow slides

### ISSUE THREAD

**Issue by theFeu** [NETWAYS/gitlab-training#209]
I think it would make more sense to add more focus on what types of branches serve which purpose, instead of explaining a strict gitflow?
We already sort of have that in the slides, but right now it feels like we are explaining a system with its components, rather than showing the components to be freely assembled into what fits your needs.
What do you think @martialblog ?

In addition we could also add some information about support branches ("contains older stable versions that still need to receive critical bug fixes but no features") - as that would be lost when we remove the two example project slides?
See my last comment in #199

**Comment by martialblog** [comment]
I think focusing more on "branches can have different roles" and be "sometimes more sometimes less permanent" is a good idea.
