### ISSUE TITLE
Idea: Remove day2/02_Integrations and use the time for more CI

### ISSUE THREAD

**Issue by martialblog** [NETWAYS/gitlab-training#216]
I think the day2/02_Integrations chapter is not that beneficial for the training, we could skip it and use the extra time for more GitLab topics. Most people are curious about CI, so that would be a good topic to extend.

**Comment by theFeu** [comment]
@htriem already has some pretty cool CI exercises prepared that he tested in a few trainings already - we'd just have to write them down and turn them into new slides :)
