### ISSUE TITLE
Add content on GitLab labels

### ISSUE THREAD

**Issue by mocdaniel** [NETWAYS/gitlab-training#232]
Labels integrate with various parts of GitLab's project management features:

- issues
- merge requests
- Kanban board

more and more participants of the training ask about labels and I think adding a small chapter demonstrating some of their features might make sense.

**Comment by martialblog** [comment]
On the slide "GitLab Issues and Boards" we already mention: "Issues can be annotated with labels." and "Kanban or Scrum board". We could add a bullet point to the Lab, "try out the board"
