### ISSUE TITLE
Better image for non-fast-foward and conflict resolution

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#29]
Do it side by side, not in a linear timeline.

<img width="994" alt="screen shot 2018-11-16 at 08 46 18" src="https://user-images.githubusercontent.com/382049/48605109-232a6e80-e97c-11e8-8277-f3c5381efbbf.png">

**Comment by dnsmichi** [comment]
For now, I really like to draw images on the whiteboard and explain that "hands on". Will think about this for the next larger changes.

**Comment by theFeu** [comment]
We came up with a nice solution with an iPad to draw on for the online trainings (that we could even use for the offline ones when no whiteboard is available.)
