### ISSUE TITLE
API: Add a simple LAB for health checks or creating a tag (advanced)

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#33]
This may be explained in the handout too, e.g. from inside CI runners to create a tag or do some more pipelining.

**Comment by dnsmichi** [comment]
This would be an advanced workflow for CI pipelines, e.g. to automatically tag something once the test & build jobs succeed.

**Comment by dnsmichi** [comment]
Should be considered for an advanced training.

**Comment by theFeu** [comment]
Moved to gitlab advanced
