### ISSUE TITLE
Restructure training with more chapters and add a recap after each chapter

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#35]
- smaller portions
- Especially a recap for
  * "3 stages"
  * rebase
  * merge, --no-ff
  * squash
  * PR/MR workflow
  * CI

**Comment by dnsmichi** [comment]
Maybe this is just too over organized. A well prepared trainer does a recap on the second day in the morning as always, but on the fly. I don't see the slides as a full blown document for self-studying either. Undecided.

**Comment by theFeu** [comment]
I agree with the well prepared trainer doing a recap. The way it goes is also highly dependant on the trainees, so we can't really have it too fixed.

Something that I started doing is preparing a set of exercises for the morning of the second day.
The trainees get to do those exercises in self study after a quick recap of day 1.

I think I might want to include these exercises somewhere.

**Comment by theFeu** [comment]
@htriem 
I sent you my latest draft, would you mind cleaning it up a little and posting it here?
I would like to go over it together to create a final version :)

**Comment by htriem** [comment]
Hey @theFeu,

**Comment by htriem** [comment]
Hey @theFeu

**Comment by htriem** [comment]
Hey @theFeu 
here are your review questions you've sent to me recently.

1. - Create a new local repository on your virtual machine
      hint: git init

2. - Add a new e-mail and user name to the local configuration of your newly created repository
    - Verify your implemented changes by printing out the local configuration of said repository
    hint: git config --local ... / git config ...


3. - Create a new README.md file in the repository and commit it
    - Show the last commit and copy the commit ID to your clipboard
    - Amend the last commit by adding new lines to your README.md file
    hint: git commit --amend
    - Compare the commit IDs of the first and the sucessive amended commit


4. - Create a new branch called 'feature/testdata'
    - Switch to the newly created branch 'feature/testdata'
    hint: git branch -> git checkout / git checkout -b


5. - Create a new directory named 'testdata' and run git status
       hint: mkdir 
    - Add an empty file named '.keep' in the new directory 'testdata' and run git status
    - Commit the new directory 'testdata' to the repository


6. - Add content to the '.keep' file and commit the changes


7. - Check out the master branch
    - Add changes to the README.md file and commit them


8. - Use git cherry-pick (with the -x flag) to apply the first commit from the 'feature/testdata' branch
    - Verify the changes by using git log


9. - Create a '.gitignore' file for the repository
    - Add the testdata directory to this '.gitignore' file and commit it
    - Verify the changes by using tig


10. - Merge the 'feature/testdata' branch with the master branch by using git merge (with the --no-ff flag)
      - Verify the changes by using tig


They helped me a lot for starting on day 2, so thank you for that once more :)

**Comment by theFeu** [comment]
Closed in favour of #118
