### ISSUE TITLE
Redraw all explanations for a more uniform look

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#36]
This should be added again.

![File lifecycle](https://git-scm.com/figures/18333fig0201-tn.png)

**Comment by theFeu** [comment]
![image](https://user-images.githubusercontent.com/22217062/98381269-f3ce0a00-2049-11eb-9b84-37167661d0a1.png)

Also a good picture. I might want to redraw it without the commands :)

**Comment by theFeu** [comment]
[git_redraw.zip](https://github.com/NETWAYS/gitlab-training/files/6677722/git_redraw.zip)

Redrew most of the images and saved them as SVGs
I will need some more time to finish them off, but looks decent so far :)

**Comment by theFeu** [comment]
This is a bit of a dated design looking at #141 - I would redo the other images from my previous comment in sketch.

**Comment by martialblog** [comment]
showoff also ships with Mermaid https://github.com/puppetlabs/showoff/blob/main/documentation/AUTHORING.rdoc#label-Rendering+Diagrams

We could draw some stuff in Markdown

**Comment by theFeu** [comment]
Looks scary, yet possible.

**Comment by martialblog** [comment]
@theFeu https://mermaid-js.github.io/mermaid/#/gitgraph

**Comment by theFeu** [comment]
Black magic!!

**Comment by martialblog** [comment]
I played around with mermaid.js some more. I think it could be a nice solution.

We can have all the Images/Graphs as text within the repo and then render them whenever something needs changing

```bash
$ docker pull minlag/mermaid-cli 
Using default tag: latest
latest: Pulling from minlag/mermaid-cli
Digest: sha256:768b5b0cfcb4c04b8b2a5db852e79cb339e0e752673af6face112577b819445e
Status: Image is up to date for minlag/mermaid-cli:latest
docker.io/minlag/mermaid-cli:latest

$ ls -l
graph.mmd

$ cat graph.mmd
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;

$ docker run -u `id -u`:`id -g` --rm -v $(pwd):/data minlag/mermaid-cli -i /data/graph.mmd 
Generating single mermaid chart

$ ls -l
graph.mmd
graph.mmd.svg
```

I will have to look at all the images, but I think that could cover most usecases
