### ISSUE TITLE
Better visualisation for git add/stage

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#39]
For example, ![stage](http://rogerdudler.github.io/git-guide/img/trees.png)

**Comment by dnsmichi** [comment]
Still a friend of drawing things during the training, undecided. Images cost extra time to create and maintain - my handwriting does not.

**Comment by theFeu** [comment]
Drawing things is preferred over having images in the training repository - binary files and whatnot :D
