### ISSUE TITLE
Provision: Update to a more recent Git version if possible

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#43]
This adds more possibilites with the native shell integration.

- Explain >, * and = for modified changes, staged, not pull etc.

**Comment by dnsmichi** [comment]
https://der-linux-admin.de/2017/11/centos-7-git-2-installieren/

**Comment by theFeu** [comment]
we wanted to rethink our machines again anyway, also with the keyring issue #110 and all that.
@Baboon92 would you mind collaborating with me on this?
