### ISSUE TITLE
Issues: Add Markdown task lists

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#56]
I'm using them on a daily basis, but this should be highlighted in the training too.

 https://docs.gitlab.com/ee/user/markdown.html#task-lists

**Comment by theFeu** [comment]
maybe we could actually look into having a mini slide on the topic of markdown after all?
what do you think my fellow trainers: @htriem @Baboon92 @mkayontour ?

**Comment by theFeu** [comment]
Covered by #119
