### ISSUE TITLE
Squash on merge request

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#7]
This was open-sourced in 11 and follows the learning curve where we already know about git squash at this stage of the training.

Participants may create multiple commits, create a MR and then squash on merge. Might be added to the LAB too.

**Comment by dnsmichi** [comment]
I'm undecided here whether this can be trained with the best success.

**Comment by theFeu** [comment]
I usually talk about the little 'squash' tick on the merge request in the lab, while it is on the screen and I go over the MR.
As we only have on commit in the lab and they know what a squash is already, I would stick with just mentioning it.
