### ISSUE TITLE
Cleanup & Healing: git gc & fsck

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#70]

**Comment by Crunsher** [comment]
I have thought about this too last week:
git gc is called by commands which may create loose files already automatically (according to the docs).
git fsck is very advanced and only relevant in extreme edge cases.

If we add those to the training they should be all the way back in a bonus chapter

**Comment by dnsmichi** [comment]
That's just a slide for the `git hints`. Good to know, but not that much to say. I've used them with homebrew-cask this week since the repo was really slow.

**Comment by theFeu** [comment]
Would maybe think about adding this to the advanced training, what do you think @N-o-X ?
