### ISSUE TITLE
Merge Strategies: Do not override my content from merge source

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#76]
This can be done with digging into the merge drivers and creating `ours` and `theirs` as config values.

```
git config --global merge.ours.driver true
```

The second step is to define the merge strategy inside the .gitattributes file.

```
vim .gitattributes
.gitlab-ci.yml merge=ours
```

https://forum.gitlab.com/t/how-to-ignore-gitlab-ci-yml-file-when-merging-the-branches/17948/4
https://medium.com/@porteneuve/how-to-make-git-preserve-specific-files-while-merging-18c92343826b

Enabling this on the GitLab server is currently not possible, at least it seems.
https://gitlab.com/gitlab-org/gitlab/issues/18830

**Comment by theFeu** [comment]
I will move this issue to the gitlab advanced, as this doesn't strike me as "basic" enough :)
