### ISSUE TITLE
Remove "Apply and Create Patches" from Git Hints chapter

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#81]
No-one uses this with MRs.

**Comment by theFeu** [comment]
I actually think it's some cool stuff to mention, and with it's placement at the end of the training it's basically just an added bonus and doesn't take anything away - so I will keep it :)

**Comment by theFeu** [comment]
( and I actually had 2 trainees in a training just recently that use patches somewhat frequently! )
