### ISSUE TITLE
Git Blame: Add how it is done via GitLab 

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#84]
Via file view and blame button `/root/training/blame/master/README.md`.

**Comment by theFeu** [comment]
Should add this to day 2, Gitlab Hints in the UI chapter.

**Comment by htriem** [comment]
We cannot add this to the Gitlab Hints in the UI chapter when discussion git blame - the command itself - only happens a chapter later in the git Hints section itself. Should I add a tutorial for usage of git blame in GUI in GitLab after those slides or do we need a bigger kind of restructuring?

**Comment by theFeu** [comment]
Move the entire git blame chapter just after they made their first 2 commits.
Also needs to be mentioned all the way in the beginning with the configuration.
