### ISSUE TITLE
CI Templates: Explain that there's a dropdown in the Web IDE to select

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#92]
That way one can e.g. compile Golang projects and similar. Encourage the trainer to open the docs and just try it out to showcase it. Also mention that there is progress with making the onboarding experience into CI better:

- https://gitlab.com/groups/gitlab-org/-/epics/2072#note_235718368

**Comment by theFeu** [comment]
closed with https://github.com/NETWAYS/gitlab-training/issues/121
