### ISSUE TITLE
Update IDEs and show real GitLab client integration screenshots

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/gitlab-training#98]
- JetBrains has them
- Visual Studio has an addon
- etc.

**Comment by theFeu** [comment]
Can you take some screens from your dev environment please? :)

The `git blame` result that you can see in each line in Intellij would be cool to show for example :)

**Comment by martialblog** [comment]
Stalled. Won't fix for now.

Also UIs might change, thus this introduced future work.
